# create some car types
Car.create(make: 'Ford', model: 'Mondeo', year: 2011)
Car.create(make: 'Ford', model: 'Focus', year: 2012)
Car.create(make: 'Ford', model: 'Fiesta', year: 2010)
Car.create(make: 'Toyota', model: 'Avensis', year: 2009)
Car.create(make: 'Toyota', model: 'Yaris', year: 2011)
Car.create(make: 'Toyota', model: 'Corolla', year: 2006)
Car.create(make: 'Toyota', model: 'Auris', year: 2011)
Car.create(make: 'Honda', model: 'Civic', year: 2012)
Car.create(make: 'Honda', model: 'Accord', year: 2010)
Car.create(make: 'Honda', model: 'Zest', year: 2113)
Car.create(make: 'Honda', model: 'Jazz', year: 2014)
Car.create(make: 'Nissan', model: 'Almera', year: 2005)
Car.create(make: 'Nissan', model: 'Juke', year: 2006)
Car.create(make: 'Nissan', model: 'Serena', year: 2007)
Car.create(make: 'Renault', model: 'Scenic', year: 2009)
Car.create(make: 'Renault', model: 'Megane', year: 2010)
Car.create(make: 'Renault', model: 'Clio', year: 2004)

# Adding some parts to the database
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '4')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '6')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '9')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '2')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '3')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '6')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '9')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '11')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '15')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '9')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '7')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '11')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '8')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '6')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '5')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '7')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '9')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '11')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '3')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '1')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '3')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '8')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '6')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '11')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '8')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '12')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '11')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '1')
Part.create(part_name: 'wheel bearing set', part_price: '50.5', car_id: '1')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '1')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '2')
Part.create(part_name: 'engine', part_price: '100.5', car_id: '2')
Part.create(part_name: 'front wing', part_price: '250.5', car_id: '3')
Part.create(part_name: 'back light lense', part_price: '70.5', car_id: '3')
Part.create(part_name: 'front grill', part_price: '100.5', car_id: '4')
Part.create(part_name: 'window wipers', part_price: '10.5', car_id: '5')
Part.create(part_name: 'alloy wheels set', part_price: '400.5', car_id: '5')
Part.create(part_name: 'brake pads', part_price: '30.5', car_id: '6')
Part.create(part_name: 'fuel filter', part_price: '17.5', car_id: '7')
Part.create(part_name: 'wheel bearing set', part_price: '75.5', car_id: '8')
Part.create(part_name: 'oil filter', part_price: '10.0', car_id: '10')
Part.create(part_name: 'wheel bearing set', part_price: '80.5', car_id: '10')
Part.create(part_name: 'front head lamp', part_price: '100.5', car_id: '16')
Part.create(part_name: 'drive', part_price: '40.5', car_id: '12')
Part.create(part_name: 'wishbone', part_price: '150.5', car_id: '17')
Part.create(part_name: 'spark plugs', part_price: '7.5', car_id: '10')
Part.create(part_name: 'sump guard', part_price: '80.5', car_id: '9')
Part.create(part_name: 'fan belt', part_price: '19.5', car_id: '13')
Part.create(part_name: 'starter motor', part_price: '120.5', car_id: '14')
Part.create(part_name: 'timing belt kit', part_price: '110.5', car_id: '15')
Part.create(part_name: 'fuel filter', part_price: '30.5', car_id: '16')
Part.create(part_name: 'oil filter', part_price: '16.5', car_id: '11')
Part.create(part_name: 'brake disks', part_price: '130.5', car_id: '8')

Employee.create(emp_name: 'Joe Bloggs', emp_address: 'Joe bloggs town', password: 'secret', password_confirmation: 'secret')
Employee.create(emp_name: 'David Ryan', emp_address: 'Saltmills New Ross', password: 'secret', password_confirmation: 'secret')
Employee.create(emp_name: 'John Finn', emp_address: 'Some town', password: 'secret', password_confirmation: 'secret')
Employee.create(emp_name: 'Adam Ryan', emp_address: 'Saltmills New Ross', password: 'secret', password_confirmation: 'secret')

